<?php
// Acces compte mysql sur isis.

$server = "localhost";
$user = "wh016159";
$password = "wh016159705b";
$base = "wh016159";

// Pour l'utiliser mettre par exemple dans votre .php qui ouvre votre base :
//   include("/users/etudiant/w/wh016159/www/.ht_mysql.inc");
//   mysql_connect("$server","$user","$password") or die("Pb connexion MySQL");
//   mysql_select_db("$base") or die("Pb selection base");
?>
